### PR TITLE
Release REUSE 3.0

### PR DESCRIPTION
**Pull request by mxmehl**
This PR prepares for the REUSE 3.0 release next week, so includes Tutorial, FAQ and Spec.

In order to display nicely, it needs some improvements in reuse-docs. Will open a PR in a minute

### CODE REVIEW

**Comment by mxmehl** [comment]
Works perfect with fsfe/reuse-docs#45

**Comment by mxmehl** [comment]
@carmenbianca @silverhook Ready for review, to be released on Wednesday :)

**Comment by mxmehl** [comment]
To test locally, please follow our README: https://github.com/fsfe/reuse-website#install

**Comment by carmenbianca** [comment]
Looks really really good! I have submitted some patches at #15.

Besides those patches, I noticed one graphics design thing: The title/section headers in the FAQ are too big for comfortable reading, and there is no table of contents.

**Comment by carmenbianca** [comment]
Another comment: It would maybe be good to link to [this change log](https://github.com/fsfe/reuse-docs/blob/master/CHANGELOG.md) somewhere on the website.

**Comment by silverhook** [comment]
I’m probably doing something wrong, but if I follow the instructions and then `hugo && hugo server`, in the resulting website I get a 404 error to Tutorial, FAQ, and Specifications; as well as Practices being pretty much an empty website.

This happens to me both on on the `release-3.0` and the `reuse-3.0-patches` branches.

**Comment by carmenbianca** [comment]
You have to do:

```
git submodule init
git submodule update
bash sync-docs.sh
hugo server
```

I think.

**Comment by silverhook** [comment]
@carmenbianca, thanks, that did it.

On `reuse-3.0-patches`, the _Tutorial_, _FAQ_, and _Specification_ pages have a bogus uncommented SPDX tag at the top.

The _Practices_ pages is still empty.

The link to specifications needs to be fixed in the _Is there a standard format for declaring copyright?_ question of the FAQ.

**Comment by carmenbianca** [comment]
> On `reuse-3.0-patches`, the _Tutorial_, _FAQ_, and _Specification_ pages have a bogus uncommented SPDX tag at the top.

I do not see this.

Ekrankopio de 2019-08-06 15-41-11

> The Practices pages is still empty.

There probably should be a redirect from /practices to /spec. Otherwise I don't know how you reached the "Practices" page.

**Comment by carmenbianca** [comment]
> The link to specifications needs to be fixed in the _Is there a standard format for declaring copyright?_ question of the FAQ.

Fixed in the newest version of https://github.com/fsfe/reuse-docs, which isn't used yet by reuse-website.

**Comment by silverhook** [comment]
Screenshot_20190806_155005

**Comment by carmenbianca** [comment]
That is unusual, because when I view the HTML source, that comment is not visible for me. Output of `hugo version`?

```
$ hugo version                                                                                                                                                                                                   
Hugo Static Site Generator v0.55.6 linux/amd64 BuildDate: unknown
```

**Comment by mxmehl** [comment]
Sorry for reacting so late, have been in a meeting.

This probably happened because it used the old version of reuse-docs. I have updated the submodule now:

```
git pull origin release-3.0    # get latest changes
git clean -dfx    # clean old stuff
bash sync-docs.sh
cd site
hugo server
```

This then also contains the correct page titles and the table of content.

Will now take a look into the suggested changes in #15 and this thread.

**Comment by mxmehl** [comment]
> Besides those patches, I noticed one graphics design thing: The title/section headers in the FAQ are too big for comfortable reading, and there is no table of contents.

Fixed with 9cb307e.

> Another comment: It would maybe be good to link to this change log somewhere on the website.

Good idea. We could certainly put it in /materials, but what about adding it on top of the specs? In  general, I would use the link from git.fsfe.org: https://git.fsfe.org/reuse/docs/src/branch/master/CHANGELOG.md

**Comment by carmenbianca** [comment]
> > Besides those patches, I noticed one graphics design thing: The title/section headers in the FAQ are too big for comfortable reading, and there is no table of contents.
> 
> Fixed with [9cb307e](https://github.com/fsfe/reuse-website/commit/9cb307ead2968142a9c2bbdd5d450ad916d2466a).

Looks better, thanks +1

> Good idea. We could certainly put it in /materials, but what about adding it on top of the specs? In general, I would use the link from git.fsfe.org: https://git.fsfe.org/reuse/docs/src/branch/master/CHANGELOG.md

Putting a link to git.fsfe.org at the top of spec.md could probably work.

---

I also noticed that the submodule was updated to `master` instead of `release-3.0` of reuse-docs. This should be verified before going live.

**Comment by mxmehl** [comment]
> There probably should be a redirect from /practices to /spec. Otherwise I don't know how you reached the "Practices" page.

Good catch! Fixed that as well now.

> I also noticed that the submodule was updated to master instead of release-3.0 of reuse-docs. This should be verified before going live.

Strange, I selected the release-3.0 branch of reuse-docs. But yes, will switch that to the 3.0 tag tomorrow anyway.

**Comment by mxmehl** [comment]
> > Good idea. We could certainly put it in /materials, but what about adding it on top of the specs? In general, I would use the link from git.fsfe.org: https://git.fsfe.org/reuse/docs/src/branch/master/CHANGELOG.md
> 
> Putting a link to git.fsfe.org at the top of spec.md could probably work.

Could you please make a proposal in reuse-docs?

**Comment by carmenbianca** [comment]
> Could you please make a proposal in reuse-docs?

Added to https://github.com/fsfe/reuse-docs/pull/47

**Comment by silverhook** [comment]
@carmenbianca, could be that this was a problem of my Hugo version, yes.

```fish
➜  ~ hugo version
Hugo Static Site Generator v0.40.1 linux/amd64 BuildDate: 2018-04-25T17:16:11Z
```

**Pull request merged**
